export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const NEW_POLL_SUCCESS = "NEW_POLL_SUCCESS";
export const NEW_POLL_FAIL = "NEW_POLL_FAIL";

export const FETCH_POLLS_SUCCESS = "FETCH_POLLS_SUCCESS";
export const FETCH_POLLS_FAIL = "FETCH_POLLS_FAIL";

export const FETCH_POLL_SUCCESS = "FETCH_POLL_SUCCESS";
export const FETCH_POLL_FAIL = "FETCH_POLL_FAIL";

export const SET_START = "SET_START";
export const SET_START_AUTH = "SET_START_AUTH";

export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAIL = "VOTE_FAIL";

export const DECLARE_SUCCESS = "DECLARE_SUCCESS";
export const DECLARE_FAIL = "DECLARE_FAIL";

export const DELETE_POLL_SUCCESS = "DELETE_POLL_SUCCESS";
export const DELETE_POLL_FAIL = "DELETE_POLL_FAIL";

